pipeline:
  name: yash-test
  identifier: yashtest
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: repoconnector
        build: <+input>
  stages:
    - stage:
        name: Clone-stage
        identifier: Clonestage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: git clone "https://github.com/Naman-cell/Harness-tester.git"
